### ISSUE TITLE
Error parsing yaml file

### ISSUE THREAD

**Issue by cjdupreez** [Soltra/crits-adapter#12]
Please have a look at my attached config, it's been sanitized to remove sensitive information.
[config.zip](https://github.com/Soltra/crits-adapter/files/89213/config.zip)

For some reason, the edgy_critsd service will not run because it says I have a syntax error. I can't find the error. 

Any help would be appreciated.

Thanks,
-Cornel.

**Comment by guitarmanvt** [comment]
@cjdupreez, there are three issues with the attached **config.yaml** file:
1. Every valid YAML file must start with three dashes. `---`. Go ahead and add that as the first line.
2. The line `    localhost: CRITS` breaks. Remove `CRITS`.
3. The line `    localhost: Soltra` breaks. Remove `Soltra`.

You can validate your YAML files online here: http://www.yamllint.com/ **NOTE:** I have no idea what that site does with samples you submit, so be sure not to submit anything private.

**Comment by guitarmanvt** [comment]
@treyka: The comment over the `localhost:` line in *.default_config.yaml* says:```
# The name you want to identify the Crits instance by
```
But the next line is indented, which makes *localhost* into a dictionary, rather than a string value. I'm not sure, but I wonder if the comment is misleading...?

**Comment by cjdupreez** [comment]
Awesome, that worked, thanks!
